GET http://127.0.0.1:8000/api/equbType/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2NTk2OTA1OTcsImV4cCI6MTY1OTY5NDE5NywibmJmIjoxNjU5NjkwNTk3LCJqdGkiOiJ1QzZ2UjlOU29KQVU2T2ltIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.WK2-WXRf-VPT1jSw3oxNpjZtruIUF8gmvuinyWNU38A