delete http://127.0.0.1:8000/api/member/delete/68
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2NTgzMDU0NTYsImV4cCI6MTY1ODMwOTA1NiwibmJmIjoxNjU4MzA1NDU2LCJqdGkiOiJQaTQ3UWJicWVDYWh0NnkzIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.1LuL_f2oNOXWYSVwJpGw8xBnq-0OTRLzoMfJP1RMBwg