GET http://127.0.0.1:8000/api/member/get-equbs/40
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2NTk3MDkxNjYsIm5iZiI6MTY1OTcwOTE2NiwianRpIjoiOHJDdFp4TzVVOUNyRzV5aSIsInN1YiI6IjQwIiwicHJ2IjoiMjNiZDVjODk0OWY2MDBhZGIzOWU3MDFjNDAwODcyZGI3YTU5NzZmNyJ9.eMxYzteeb9NdMycbuedYLf5qccceAHwh2AdlMzLYzU8