GET http://127.0.0.1:8000/api/member/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2NTkwMTE5MjAsImV4cCI6MTY1OTAxNTUyMCwibmJmIjoxNjU5MDExOTIwLCJqdGkiOiJESEdDeWlndjZHN0ZYd1BCIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.w_oB4p7or2b-VqlcG1npNi7RZdS1y1BIE8GjIN7cyeY