GET http://127.0.0.1:8000/api/member/get-equbs/17
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2NTkxMDA3NjYsImV4cCI6MTY1OTEwNDM2NiwibmJmIjoxNjU5MTAwNzY2LCJqdGkiOiJuRGFiMHI4b2d6U2taOWtrIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.E2wHKX9Rp03ZSjfW6r_73xlPlQUvsRUFd_j9l6KVVwc