<?php
return [
    'FIREBASE_SERVER_KEY' => env('FIREBASE_SERVER_KEY'),
    'HAHU_CLOUD_API' => env('HAHU_CLOUD_API'),
    'HAHU_DEVICE_ID' => env('HAHU_DEVICE_ID'),
    'AFRO_API_KEY' => env('AFRO_API_KEY'),
    'AFRO_IDENTIFIER_ID' => env('AFRO_IDENTIFIER_ID'),
    'AFRO_SENDER_NAME' => env('AFRO_SENDER_NAME'),
    'AFRO_BASE_URL' => env('AFRO_BASE_URL'),
    'AFRO_SPACE_BEFORE_OTP' => env('AFRO_SPACE_BEFORE_OTP'),
    'AFRO_SPACE_AFTER_OTP' => env('AFRO_SPACE_AFTER_OTP'),
    'AFRO_OTP_EXPIRES_IN_SECONDS' => env('AFRO_OTP_EXPIRES_IN_SECONDS'),
    'AFRO_OPT_LENGTH' => env('AFRO_OPT_LENGTH'),
    'AFRO_OTP_TYPE' => env('AFRO_OTP_TYPE'),
    'SHORT_CODE' => env('SHORT_CODE'),
    "TELEBIRR_APP_ID" => env('TELEBIRR_APP_ID'),
    "TELEBIRR_RECEIVER_NAME" => env('TELEBIRR_RECEIVER_NAME'),
    "TELEBIRR_SHORT_CODE" => env('TELEBIRR_SHORT_CODE'),
    "TELEBIRR_SUBJECT" => env('TELEBIRR_SUBJECT'),
    "TELEBIRR_RETURN_URL" => env('TELEBIRR_RETURN_URL'),
    "TELEBIRR_NOTIFY_URL" => env('TELEBIRR_NOTIFY_URL'),
    "TELEBIRR_TIMEOUT_EXPRESS" => env('TELEBIRR_TIMEOUT_EXPRESS'),
    "TELEBIRR_APP_KEY" => env('TELEBIRR_APP_KEY'),
    "TELEBIRR_INAPP_PAYMENT_URL" => env('TELEBIRR_INAPP_PAYMENT_URL'),
    "TELEBIRR_PUBLIC_KEY" => env('TELEBIRR_PUBLIC_KEY', "-----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmSvHmZwuQjZbD+X6qxJZIjms4kyEo/tRJGt66F/aUkIrsoMaY/kIS+hgiUhcQi1Lem0DDCb+CHAaSf/YiiCmdhXhaSDckMgZvIzcAZhQX0pHtZhbim9G/0/ekrm7JWCq0+YJ7KF5xcWtRNyHpVKi6snpqsAVp9o8rsMHPhn4YvLZGVUapONRwtmBJ5YLJdkmMD9FU1r/B+yl8lIQjr3iVHMaCQXbEv7mF34FP9wDm5kvysSsthZ6APzJMWTswNCDIgVrbmXOvyOxd3x8PNCFkwwH4BrLxsmyDY7KnXm55oqOukeYODtG3AShnwVFDn7G/7mdI8vEURHkwbVT4SuQJwIDAQAB
    -----END PUBLIC KEY-----"),
    "TELEBIRR_PUBLIC_KEY_C" => env('TELEBIRR_PUBLIC_KEY_C'),
    "TELEBIRR_H5_URL" => env('TELEBIRR_H5_URL', "https://app.ethiomobilemoney.et:2121/ammapi/payment/service-openup/toTradeWebPay"),
    
    
    
    'TELEBIRR_BASE_URL' => env('TELEBIRR_BASE_URL'),
    'TELEBIRR_FABRIC_APP_ID' => env('TELEBIRR_FABRIC_APP_ID'),
    'TELEBIRR_APP_SECRET' => env('TELEBIRR_APP_SECRET'),
    'TELEBIRR_MERCHANT_APP_ID' => env('TELEBIRR_MERCHANT_APP_ID'),
    'TELEBIRR_MERCHANT_CODE' => env('TELEBIRR_MERCHANT_CODE'),
    'TELEBIRR_TITLE' => env('TELEBIRR_TITLE'),
    'PRIVATE_KEY' => env('PRIVATE_KEY'),

    'JWT_SECRET' => env('JWT_SECRET'),
    'APP_ENV' => env('APP_ENV'),
    'APP_DEBUG' => env('APP_DEBUG'),

    'CBE_MINI_COMPANY_NAME' => env('CBE_MINI_COMPANY_NAME'),
    'CBE_MINI_HASHING_KEY' => env('CBE_MINI_HASHING_KEY'),
    'CBE_MINI_TILL_CODE' => env('CBE_MINI_TILL_CODE'),
    'FIREBASE_SERVER_KEY' => env('FIREBASE_SERVER_KEY'),
];
