GET http://127.0.0.1:8000/api/payment/3/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2NTk2MjAxNDgsImV4cCI6MTY1OTYyMzc0OCwibmJmIjoxNjU5NjIwMTQ4LCJqdGkiOiJLNktCODJndGZaRENRU2JxIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.fIwleCCj6qyszx0vvftWNdemWwuYn6VXQAjf-QjXgSM