GET http://127.0.0.1:8000/api/dashboard
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2NTk5NDkxOTksIm5iZiI6MTY1OTk0OTE5OSwianRpIjoic0QzZUZQdzRpT0hpNXg1MyIsInN1YiI6IjEiLCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.IqZsA0kjKbM4waHigSLV9djJ_GeN1xXk3tZ-mr1jF14