GET http://127.0.0.1:8000/api/reports/lotterys/2022-04-27/2022-08-27/6/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjgwMDAvYXBpL2F1dGgvbG9naW4iLCJpYXQiOjE2NTgzMDAzOTQsImV4cCI6MTY1ODMwMzk5NCwibmJmIjoxNjU4MzAwMzk0LCJqdGkiOiJWclc5TmVEOWYxSmhaN28zIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.YnDE2ca8eGuY1N4-XSEZZ5XmJpJaT6u4KAbwdZz-W9c